---
tap_install:
  values:
    profile: full

    shared:
      ingress_domain: tap.ss.cloudmonk.me
      ingress_issuer: ""
      image_registry:
        project_path: tap30c5a3c2.azurecr.io/tap/tap-images # Image registry project path (e.g. myregistry.azurecr.io/tap/tap-images)
        username: tap30c5a3c2

    cnrs:
      default_tls_secret: contour-tls/tls
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}" # this is a go-template

    ceip_policy_disclosed: true

    # These packages will be deprecated in future versions of TAP, so we will exclude them to free up space on the cluster
    excluded_packages:
      - eventing.tanzu.vmware.com

    tap_gui:
      service_type: ClusterIP
      ingressEnabled: "true"
      app_config:
        auth:
          allowGuestAccess: true
          environment: development
      tls:
        namespace: contour-tls
        secretName: tls

    namespace_provisioner:
      controller: false
      sync_period: 30s
      # configure a repo that defines which namespaces should exist
      # for simplicity, it's the same one we have been using
      gitops_install:
        ref: origin/main
        subPath: clusters/workshop/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/samarsinghal/workshop-clusters.git
        secretRef:
          name: sync-git
          namespace: tanzu-sync
          create_export: true
